### ISSUE TITLE
How to work it?

### ISSUE THREAD

**Issue by PhazerPlays** [codingWithBobby/-Automate-Free-Kr-With-Python#1]

**Comment by PhazerPlays** [comment]
is it a tampermonkey script

**Comment by codingWithBobby** [comment]
No. It isnt a hack. Just download python. and then download it. The main
script is the  one called openKrunker.py. Once you have the free Kr button
Avaible run the script it opens up krunker and clicks on it does the spin
and then wait 2 hours and 1 minute before it does it again

**Comment by codingWithBobby** [comment]
This was made more as a fun side coding projects than an actual Krunker one.

**Comment by codingWithBobby** [comment]
I recommend downloading sublime text 3 to run it. Just open up the file, openKrunker.py and click crtl +b to run it

**Comment by codingWithBobby** [comment]
I was looking over the code and realized that it will only work if you have two 24" monitors because I wrote a function that makes the mouse go to a specific part of the screen.
